load("//bazel:rules_apple.bzl", "submodule", "submodule_unit_test", "submodule_dynamic")

submodule_unit_test(
    name = "__MODULE_NAME__",
	visibility = ["//visibility:public"],
	deps = [
		# "//Vendor:AsyncDisplayKit"
	]
)
