config_setting(
    name = "develop",
    values = {
        "define": "scheme=develop",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "staging",
    values = {
        "define": "scheme=staging",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "release",
    values = { 
        "define": "scheme=release",
    },
    visibility = ["//visibility:public"],
)