config_setting(
    name = "develop",
    values = {
        "define": "environment=develop",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "release",
    values = { 
        "define": "environment=release",
    },
    visibility = ["//visibility:public"],
)