#!/bin/bash -eu

readonly bazel_platform="darwin"
readonly tulsi_script="$PWD/scripts/tulsiw"

if [[ ! -d $1 ]]; then
	echo "$0 must be run from the BazelSample directory"
	exit 1
fi

exec "${tulsi_script}" \
	--genconfig "$1:$2" --no-open-xcode
