load("//bazel:rules_apple.bzl", "submodule", "submodule_unit_test", "submodule_dynamic")

submodule_unit_test(
    name = "SwiftLib",
	visibility = ["//visibility:public"],
	deps = [
		"//Vendor:AsyncDisplayKit"
	]
)
